### ISSUE TITLE
Visuals do not scale down properly

### ISSUE THREAD

**Issue by abn2609** [Tucsky/SignificantTrades#101]
Sizing it to a quarter screen seems to mess up the display for ETHUSD.aggr compared to regular and other alt coins.
All you can see is the chart and the Sig trades bar does not even show unless maximised back.

Thanks Tucsky

**Comment by Tucsky** [comment]
Hmm not sure Im getting what you mean but when window is small everything is placed on top of each other, so if its too short u will have to scroll to see trades...

**Comment by Tucsky** [comment]
there was an issue with the vertical scrolling when screen > 500px, I just fixed it let me know if thats better

**Comment by abn2609** [comment]
If I place it side by side vs 3 other coins, you'll see it still doesn't
match up with the scaling. See below: Even the chart legend font is huge.

Cheers!

[image: image.png]

**Comment by Tucsky** [comment]
>See below: Even the chart legend font is huge

No I can't see

**Comment by Tucsky** [comment]
![bug](https://user-images.githubusercontent.com/5738336/84494375-abccd600-aca9-11ea-9d8e-09e0a76791d5.gif)
this ?

**Comment by abn2609** [comment]
You can't see the image I attached?
